export interface Product {
  id: number;
  name: string;
  price: number;
  description: string;
}

export const products = [
  {
    id: 1,
    link: 'https://www.amazon.com/Google-Pixel-XL-Not-Pink/dp/B07KGMQ5WQ/ref=sr_1_1?keywords=google+pixel+3xl&qid=1648650705&sr=8-1',
    image: 'https://m.media-amazon.com/images/I/71duHoxxLnL._AC_SL1500_.jpg',
    name: 'Pixel 3 XL',
    price: 799,
    description: 'A large phone with one of the best screens',
    category: 'phone',
    rating: 4,
  },
  {
    id: 2,
    link: 'https://www.amazon.com/Apple-iPhone-12-Pro-Pacific/dp/B09JFNMBWL/ref=sr_1_1?crid=1VLYJHK9AHZ0T&keywords=Apple+iPhone+12+Pro&qid=1648650745&sprefix=apple+iphone+12+pro%2Caps%2C237&sr=8-1',
    image: 'https://m.media-amazon.com/images/I/712yl2wTDbL._AC_SL1500_.jpg',
    name: 'Apple iPhone 12 Pro',
    price: 899,
    description: 'A great phone with one of the best cameras',
    category: 'phone',
    rating: 3,
  },
  {
    id: 3,
    link: 'https://www.amazon.com/Apple-iPhone-12-64GB-Black/dp/B09JFNTCLX/ref=sr_1_1?crid=38HN9RFKRS1QO&keywords=Apple+iPhone+12&qid=1648650769&sprefix=apple+iphone+12%2Caps%2C233&sr=8-1',
    image: 'https://m.media-amazon.com/images/I/81AaNJqE+wS._AC_SL1500_.jpg',
    name: 'Apple iPhone 12',
    price: 659,
    description: 'desc for phone',
    category: 'phone',
    rating: 5,
  },
  {
    id: 4,
    link: 'https://www.amazon.com/Apple-iPhone-256GB-Unlocked-Renewed/dp/B07ZQRL9XY/ref=sr_1_1?crid=3OXTSWKB05G17&keywords=Apple+iPhone+11+Pro&qid=1648650801&sprefix=apple+iphone+11+pro%2Caps%2C230&sr=8-1',
    image: 'https://m.media-amazon.com/images/I/81LmL94PUvS._AC_SL1500_.jpg',
    name: 'Apple iPhone 11 Pro',
    price: 299,
    description: 'desc for phone',
    category: 'phone',
    rating: 5,
  },
  {
    id: 5,
    link: 'https://www.amazon.com/Apple-iPhone-12-Pro-Max/dp/B09JF9WMR9/ref=sr_1_1?crid=1SLK483QNWHZU&keywords=iPhone+12+Pro+Max&qid=1648650816&sprefix=iphone+12+pro+max%2Caps%2C243&sr=8-1',
    image:
      'https://images-na.ssl-images-amazon.com/images/I/71FuI8YvCNL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    name: 'iPhone 12 Pro Max',
    price: 1000,
    description: 'desc for phone',
    category: 'phone',
    rating: 3,
  },
  {
    id: 6,
    link: 'https://www.amazon.com/Apple-iPhone-SE-64GB-Black/dp/B088NQXD8T/ref=sr_1_1?crid=2K4YQJWPIBULG&keywords=iPhone+SE+2nd+gen&qid=1648650844&sprefix=iphone+se+2nd+gen%2Caps%2C410&sr=8-1',
    image:
      'https://m.media-amazon.com/images/I/81K+adaNRiL._AC_SY300_SX300_.jpg',
    name: 'iPhone SE 2nd gen',
    price: 299,
    description: 'desc for phone',
    category: 'phone',
    rating: 4,
  },
  {
    id: 7,
    link: 'https://www.amazon.com/Apple-iPhone-Fully-Unlocked-128GB/dp/B01N25DJ2B/ref=sr_1_1?crid=12JRY3K3A8UWI&keywords=iPhone+7&qid=1648650857&sprefix=iphone+7%2Caps%2C278&sr=8-1',
    image:
      'https://m.media-amazon.com/images/I/31+rHqWgOrL._AC_SY300_SX300_.jpg',
    name: 'iPhone 7',
    price: 399,
    description: 'desc for phone',
    category: 'phone',
    rating: 3,
  },
  {
    id: 8,
    link: 'https://www.amazon.com/Tracfone-Motorola-Moto-Stylus-128GB/dp/B09CLNH78M/ref=sr_1_3?crid=3ULF4AM1K3AIR&keywords=Tracfone+Motorola+Moto+g+Stylus&qid=1648650880&sprefix=tracfone+motorola+moto+g+stylus%2Caps%2C218&sr=8-3',
    image: 'https://m.media-amazon.com/images/I/41fndFl92zL._AC_SR160,160_.jpg',
    name: 'Tracfone Motorola Moto g Stylus',
    price: 129,
    description: 'desc for phone',
    category: 'phone',
    rating: 5,
  },
  {
    id: 9,
    link: 'https://www.amazon.com/Tracfone-Motorola-Moto-Power-Grove/dp/B09NWDX31H/ref=sr_1_3?crid=3O68W3QPKWHIN&keywords=Tracfone+Motorola+Moto+g+Power&qid=1648650898&sprefix=tracfone+motorola+moto+g+power%2Caps%2C226&sr=8-3',
    image: 'https://m.media-amazon.com/images/I/41wdk3YcNbL._AC_SR160,160_.jpg',
    name: 'Tracfone Motorola Moto g Power',
    price: 149,
    description: 'desc for phone',
    category: 'phone',
    rating: 1,
  },
  {
    id: 10,
    link: 'https://www.amazon.com/CUBOT-Unlocked-Smartphones-Display-Android/dp/B08FT6SN4G/ref=sr_1_3?crid=POBFZYJJ6JQN&keywords=CUBOT+Smartphone&qid=1648650920&sprefix=cubot+smartphone%2Caps%2C235&sr=8-3',
    image: 'https://m.media-amazon.com/images/I/41pLj58aDNL._AC_SR160,160_.jpg',
    name: 'CUBOT Smartphone',
    price: 169,
    description: 'desc for phone',
    category: 'phone',
    rating: 3,
  },
  {
    id: 11,
    link: 'https://www.amazon.com/PASER-Gallon-Motivational-Perfect-Workout/dp/B09MD4PZPD?ref=dlx_deals_gd_dcl_img_15_c2546324_dt_sl15_b4',
    image:
      'https://m.media-amazon.com/images/I/71Q5s5TVuPL._AC_SX466_.jpg,160_.jpg',
    name: 'PASER Half Gallon Water Bottle',
    price: 19,
    description: 'desc for bottle',
    category: 'bottle',
    rating: 5,
  },
  {
    id: 12,
    link: 'https://www.amazon.com/Simple-Modern-Water-Bottle-Silicone/dp/B09C92F7BG/ref=sr_1_2?crid=2QZ92A9ZOLFZL&keywords=bottle&qid=1648698990&sprefix=bottle%2Caps%2C238&sr=8-2',
    image: 'https://m.media-amazon.com/images/I/41e70H7464L._AC_SY879_.jpg',
    name: 'Simple Modern 1 Gallon Water Bottle',
    price: 169,
    description: 'desc for bottle',
    category: 'bottle',
    rating: 5,
  },
  {
    id: 13,
    link: 'https://www.amazon.com/adidas-Stadium-Plastic-Water-Bottle/dp/B081SJHVRN/ref=sr_1_8?keywords=bottle&qid=1648699092&sr=8-8',
    image: 'https://m.media-amazon.com/images/I/61UNgdoZSJS._AC_SX522_.jpg',
    name: 'adidas Stadium 750 ML',
    price: 169,
    description: 'desc for bottle',
    category: 'bottle',
    rating: 3,
  },
  {
    id: 14,
    link: 'https://www.amazon.com/Michael-Kors-Runway-Black-MK8507/dp/B01HEVAPSO/ref=sr_1_6?crid=1JYPD89FNX2AS&keywords=watch&qid=1648699240&sprefix=watch%2Caps%2C239&sr=8-6',
    image: 'https://m.media-amazon.com/images/I/71sMS5i3wxL._AC_UX679_.jpg',
    name: 'Michael Kors Runway Black MK8507',
    price: 169,
    description: 'desc for watch',
    category: 'watch',
    rating: 3,
  },
  {
    id: 15,
    link: 'https://www.amazon.com/Fossil-Stainless-Steel-Touchscreen-Smart/dp/B09B2WWVBR/ref=sr_1_7?crid=1JYPD89FNX2AS&keywords=watch&qid=1648699277&sprefix=watch%2Caps%2C239&sr=8-7',
    image: 'https://m.media-amazon.com/images/I/71Gtzq2yqnL._AC_UX679_.jpg',
    name: 'Fossil Mens Gen 6',
    price: 169,
    description: 'desc for watch',
    category: 'watch',
    rating: 3,
  },
  {
    id: 16,
    link: 'https://www.amazon.com/Donerton-Smartwatch-Waterproof-Activity-Pedometer/dp/B08DTF6YYD/ref=sr_1_9?crid=2Y20NU0NSCWIO&keywords=watch&qid=1648699349&sprefix=watch%2Caps%2C246&sr=8-9',
    image: 'https://m.media-amazon.com/images/I/61sWtUsCuZL._AC_SX425_.jpg',
    name: 'Donerton Smart Watch',
    price: 169,
    description: 'desc for watch',
    category: 'watch',
    rating: 3,
  },
  {
    id: 17,
    link: 'https://www.amazon.com/Vlogging-Camera-Digital-YouTube-Batteries/dp/B09TZVX3KK/ref=sr_1_5?crid=3CU2GDA5P4HDX&keywords=camera&qid=1648699498&sprefix=camera%2Caps%2C242&sr=8-5',
    image: 'https://m.media-amazon.com/images/I/81pgsjFGpmL._AC_SX425_.jpg',
    name: 'Vlogging Camera',
    price: 169,
    description: 'desc for camera',
    category: 'camera',
    rating: 3,
  },
  {
    id: 18,
    link: 'https://www.amazon.com/Canon-Rebel-T7-18-55mm-II/dp/B07C2Z21X5/ref=sr_1_8?crid=3CU2GDA5P4HDX&keywords=camera&qid=1648699498&sprefix=camera%2Caps%2C242&sr=8-8',
    image: 'https://m.media-amazon.com/images/I/71EWRyqzw0L._AC_SX522_.jpg',
    name: 'Canon EOS Rebel T7 DSLR ',
    price: 169,
    description: 'desc for camera',
    category: 'camera',
    rating: 3,
  },
  {
    id: 19,
    link: 'https://www.amazon.com/VJIANGER-Autofocus-Vlogging-Photography-Batteries/dp/B09774BTKG/ref=sr_1_3?crid=3CU2GDA5P4HDX&keywords=camera&qid=1648699415&sprefix=camera%2Caps%2C242&sr=8-3',
    image: 'https://m.media-amazon.com/images/I/71VM+34luML._AC_SX425_.jpg',
    name: 'VJIANGER 4K Digital Camera',
    price: 169,
    description: 'desc for camera',
    category: 'camera',
    rating: 3,
  },
  {
    id: 20,
    link: 'https://www.amazon.com/Cottonelle-ComfortCare-CleaningRipples-Biodegradable-Septic-Safe/dp/B07ND3MW45/ref=sr_1_5?keywords=toilet+paper&qid=1648699597&sprefix=to%2Caps%2C234&sr=8-5',
    image: 'https://m.media-amazon.com/images/I/81G2PgoP-SL._AC_SX425_.jpg',
    name: 'Cottonelle Ultra Comfort Toilet Paper',
    price: 169,
    description: 'desc for paper',
    category: 'paper',
    rating: 5,
  },
  {
    id: 21,
    link: 'https://www.amazon.com/Charmin-Strong-Toilet-Family-Packaging/dp/B0798DVT69/ref=sr_1_6?keywords=toilet+paper&qid=1648699656&sprefix=to%2Caps%2C234&sr=8-6',
    image:
      'https://m.media-amazon.com/images/I/81SRhCfNu3L._AC_SX425_PIbundle-3,TopRight,0,0_SH20_.jpg',
    name: 'Charmin Ultra Strong Clean Touch Toilet Paper',
    price: 169,
    description: 'desc for paper',
    category: 'paper',
    rating: 5,
  },
  {
    id: 22,
    link: 'https://www.amazon.com/Amazon-Basics-2-Ply-Toilet-Paper/dp/B095CN96JS/ref=sr_1_7?keywords=toilet+paper&qid=1648699656&sprefix=to%2Caps%2C234&sr=8-7',
    image: 'https://m.media-amazon.com/images/I/81pmLwW-+iL._AC_SX522_.jpg',
    name: 'Amazon Basics 2-Ply Toilet Paper',
    price: 169,
    description: 'desc for paper',
    category: 'paper',
    rating: 5,
  },
];

/*
Copyright Google LLC. All Rights Reserved.
Use of this source code is governed by an MIT-style license that
can be found in the LICENSE file at https://angular.io/license
*/
